version: 0.2.1.{build}
branches:
  only:
  - master
assembly_info:
  patch: true
  file: src\NTextCatLib\Properties\CommonAssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
platform: Any CPU
configuration: Release
build:
  parallel: true
  project: src\NTextCat\NTextCat.csproj
