version: 0.2.1.{build}
branches:
  only:
    - master
cache:
  packages -> **\packages.config
assembly_info:
  patch: true
  file: src\NTextCat\Properties\CommonAssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
platform: AnyCPU
configuration: Release
build:
  parallel: true
  project: src\NTextCat\NTextCat.csproj
test:
  # assemblies to test - optional
  assemblies:
    - **\*.Test.dll
# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true
