version: 0.2.1.{build}
branches:
  only:
    - master
skip_tags: true
clone_depth: 50
cache:
  packages -> **\packages.config
assembly_info:
  patch: true
  file: src\NTextCat\Properties\CommonAssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
platform: Any CPU
configuration: Release
build:
  # parallel: true
  project: src\NTextCat.sln
  publish_nuget: true
  publish_nuget_symbols: true
after_build:
  - ps: Get-ChildItem -Recurse .
test:
  assemblies:
    - '**\*.Test.dll'
  #  - src\NTextCat.Test\bin\Release\NTextCat.Test.dll
# Automatically register private account and/or project AppVeyor NuGet feeds.
after_test:
  - echo nuget pack src\NTextCat\NTextCat.csproj -IncludeReferencedProjects -Symbols -Prop Configuration=%CONFIGURATION%
  - nuget pack src\NTextCat\NTextCat.csproj -IncludeReferencedProjects -Symbols -Prop Configuration=%CONFIGURATION% -Verbose
  - ps: Get-ChildItem -Recurse .
artifacts:
  - path: '**\NTextCat.*.nupkg'
  - path: src\NTextCat\bin\$(configuration)
    name: NTextCat binaries
    type: zip
