# version format
version: 0.3.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

skip_commits: 
  message: /NO_BUILD/

image: Visual Studio 2019

install:
  # to avoid a build error "project.assets.json not found"
  - dotnet restore ./src

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
  parallel: true                  # enable MSBuild parallel builds
  project: src/NTextCat/NTextCat.csproj       # path to Visual Studio solution or project
  publish_nuget: false             # package projects with .nuspec files and push to 

after_build:
- cmd: botnet pack ./src/NTextCat/NTextCat.csproj

artifacts
- path: '**\*.nupkg'

deploy:
  - provider: NuGet
    skip_symbols: false     # generate and publish NuGet symbol packages
    api_key:
      secure: HsYsJEJ+1QjI7I2ZTGzCtwqohFlYK67CUq4xemWtdBfhjOpwdWD7sTNVbcG0Lg32
    

for:    
  -
    branches:
      only:
        - master

    configuration: Release
        
    dotnet_csproj:
      patch: true
      file: '**\*.csproj'
      version: '{version}'
      package_version: '{version}'
      assembly_version: '{version}'
      file_version: '{version}'
      informational_version: '{version}'

  -
    configuration: Debug
        
    dotnet_csproj:
      patch: true
      file: '**\*.csproj'
      version: '{version}'
      package_version: '{version}-{branch}'
      assembly_version: '{version}'
      file_version: '{version}'
      informational_version: '{version}-{branch}'
      informational_version: '{version}-{branch}'
