version: 0.2.1.{build}
branches:
  only:
    - master
cache:
  packages -> **\packages.config
assembly_info:
  patch: true
  file: src\NTextCat\Properties\CommonAssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
platform: AnyCPU
configuration: Release
build:
  parallel: true
  project: src\NTextCat\NTextCat.csproj
after_build:
  - ps: Get-ChildItem -Recurse .
test:
  # assemblies to test - optional
  assemblies:
  #  - '**\*.Test.dll'
    - src\NTextCat.Test\bin\Release\NTextCat.Test.dll
# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true
after_test:
  - ps: nuget pack src\NTextCat\NTextCat.nuspec
  - ps: Get-ChildItem -Recurse .
artifacts:
  - path: 'src\NTextCat\NTextCat.*.nupkg'
